version: '3.8'  # Especifica la versión de Compose

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - db
    networks:
      - sonarnet
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube_b1d88f9419ef949ae56
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped  # Añadir política de reinicio

  db:
    image: postgres:15.2-alpine
    container_name: sonarqube_db
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube_b1d88f9419ef949ae56
      POSTGRES_DB: sonarqube
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  # Añadir política de reinicio

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - sonarqube
    networks:
      - sonarnet
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped  # Añadir política de reinicio

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:

networks:
  sonarnet:
    driver: bridge
